### ISSUE TITLE
Vote Bomb error

### ISSUE THREAD

**Issue by alecm858** [HackerParachuteBattalion/scream#2]
[deleted]

**Comment by thelafffinman** [comment]
There are going to be lots of issues as Yik Yak's APIs have changed
significantly since this script was first written causing most of the
scripts functionality to stop functioning. There is a possibility that
we'll update it, but if we do it will take a while. They started
obfuscating the app and none of the script's authors are in school anymore
and have work and stuff.

For now, we're not planning on any updates that aren't easy to fix. If
there's something that doesn't require reversing the current version of the
app (like the 8-bit byte string error), I'm more than happy to fix it. To
be honest we never expected anyone would use it beyond the few of us who
worked on it. But, seeing that there is interest we're considering giving
it another go.
